:imagesdir: images

= Guía de instalación en Ubuntu 20.04 de los requisitos mínimos de Zahorí
:revdate: {docdate}
:toc: left
:toclevels: 3
:sectnums:
:sectanchors:
:Author: Zahori Panel Team
:revnumber: latest
:icons: font
:source-highlighter: coderay
:docinfo: shared


[cols=2*,options="header"]
.Requisitos del Entorno de Desarrollo Ubuntu 20.04 LTS
|===
|Nombre Aplicación
|Version

|Git
|2.25.1

|JDK de Java
|11.0.10.j9-adpt

|Maven
|3.6.3

|Docker
|20.10.5

|docker-compose
|1.25.0
|===

<<<

La documentación se ha validado con Ubuntu 20.04.2 LTS 64 bits.

= Instalación de la herramienta de control de versiones (GIT)
<<<

En esta distribución suele venir git instalado. Abrimos un terminal y comprobamos si está instalado:


----
$ git --version
  git version 2.25.1
----


<<<

En el caso de que no devuelva versión:

----
$ sudo apt update && apt install git
----


<<<

Ya tenemos git instalado, procedemos a identificamos con nuestros datos de usuario y correo electrónico escribiendo en el terminal:


----
$ git config --global user.name "Mi Usuario"
----

----
$ git config --global user.email "micorreoelectronico"
----



= Instalación del JDK de Java y Maven

<<<

Abrimos un terminal e introducimos:


----
$ sudo apt install curl
$ curl -s "https://get.sdkman.io" | bash
----

<<<

**Abrimos un nuevo Terminal Bash** y ejecutamos 
----
$  source "$HOME/.sdkman/bin/sdkman-init.sh"
----


<<<

Instalamos el jdk:

----
$ sdk install java 11.0.10.hs-adpt
----


<<<

Instalamos Maven:

----
$ sdk install maven
----



= Instalación de Docker

<<<

Desinstalamos versiones anteriores. Abrimos un terminal e introducimos:

----
$ sudo apt-get remove docker docker-engine docker.io containerd runc
----


<<<

Eliminamos imágenes, volúmenes, contenedores, configuración anteriores. Abrimos un terminal e introducimos:

----
$ sudo rm -rf /var/lib/docker
----

----
$ sudo rm -rf /var/lib/containerd
----


<<<

Instalamos Docker a través de su repositorio oficial. Instalamos la fuente del apt oficial. Abrimos un terminal e introducimos:

----
$ sudo apt-get update
----

----
$ sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
----

----
$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
----

----
$ echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
----

<<<

Instalamos Docker Engine. Abrimos un terminal e introducimos:

----
$ sudo apt-get update
----

----
$ sudo apt-get install docker-ce docker-ce-cli containerd.io
----

<<<

Para utilizar Docker con un usuario no root. Abrimos un terminal e introducimos:

----
$ sudo groupadd docker
----


----
$ sudo usermod -aG docker $USER
----

----
$ sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
----

----
$ sudo chmod g+rwx "$HOME/.docker" -R
----

----
$ newgrp docker
----

= Instalación de Docker Compose

<<<

Instalamos Docker Compose con pip. Abrimos un terminal e introducimos:

----
$ sudo apt install -y python3 python3-pip
----

----
$ sudo pip3 install docker-compose
----

----
$ docker-compose -v
  docker-compose version 1.25.0, build unknown
----

<<<

= Próximos pasos
Descarga el proceso de ejemplo: https://github.com/zahori-io/zahori-doc#2-descarga-el-proceso-de-ejemplo

<<<
